### PR TITLE
164 better clarification and description of development and released versions of the fmi ls bus on the fmi ls bus landing page

### PR DESCRIPTION
**Pull request by bmenne-dspace**
In order to better attract external readers, released (alpha, beta, final) versions and defined milestones of the fmi-ls-bus shall be prominent placed at the fmi-ls-bus landing page. Also the current link to the html document (from master branch) shall be explicit declared and described as development version within the fmi-ls-bus landing page, as it becomes very confusing as soon as you don't attend to the FMI design meetings.

In order to give external readers a better overview of the current development status and future work, we have also integrated an overview of the roadmap discussed, as well as a detailed version (without dates) on the FMI-LS-bus landing page.

To give you a better chance to see the new landing page "in action" I published it at a fork of this repo: https://github.com/bmenne-dspace/fmi-ls-bus?tab=readme-ov-file

If you wish, we can discuss and show the whole thing at one of the next FMI design meetings (next tuesday I´m on vacation). But I have no feeling whether the whole thing is suitable for a larger group or whether it is simply too unimportant.

### CODE REVIEW

**Review by chrbertsch — COMMENTED** [review]
I like this very much!

Questions on the detailed roadmap: 

- Do the boxes belong to the milestones before or after them? My understanding is "after". But shouldn't the 1.0.0alpha milestone then not be green and 1.0.0beta red?
- Should the names such as "1.0 Beta" not belong to the milestone circles instead of the boxes?
- What does "1.0 development" mean?

**Review by chrbertsch — COMMENTED** [review]
@bmenne-dspace : Could you please upload also the re-generated roadmap.svg file?

**Comment by bmenne-dspace** [comment]
@chrbertsch thanks for your feedback. I updated the PullReq and also the fork: https://github.com/bmenne-dspace/fmi-ls-bus?tab=readme-ov-file

**Review by chrbertsch — APPROVED** [review]

**Comment by bmenne-dspace** [comment]
Decision of FMI Design Meeting (06-04-2024): PR can be merged

**Pull request merged**
