### PR TITLE
Fixed issue 57

### PR DESCRIPTION
**Pull request by bmenne-dspace**
Fixed issue #57

I think it's more straight-forward now.

### CODE REVIEW

**Comment by bmenne-dspace** [comment]
@andreas-junghanns do you think we can merge that PR?

**Comment by andreas-junghanns** [comment]
> @andreas-junghanns do you think we can merge that PR?

Sorry, I still don't understand the sentence on line 114...

**Comment by bmenne-dspace** [comment]
> > @andreas-junghanns do you think we can merge that PR?
> 
> Sorry, I still don't understand the sentence on line 114...

"Using this type of architecture allows the support of this layered standard for non-primary FMI importers by using proprietary extension mechanisms." --> The whole thing means: If you have e.g. a simulator that already supports buses (but not yet the fmi-ls-bus) then you can build an interface that transforms the fmi-ls-bus data into your proprietary bus interface. The communication in the simulator can then take place via the proprietary bus interface and on the receiver side it is transformed back to fmi-ls-bus data.

The sentence seemed important to me, because you can show others that you can also expand your proprietary interface with the fmi-ls bus and don't have to solve it completely using FMI means. It thus lowers the hurdle for supporting the fmi-ls-bus and strengthens the acceptance of the standard.

Maybe we should make this sentence more clearer?

**Comment by andreas-junghanns** [comment]
I like the sentence in your comment much better as a base for what should be in the text: "If you have e.g. a simulator that already supports buses (but not yet the fmi-ls-bus) then you can build an interface that transforms the fmi-ls-bus data into your proprietary bus interface. The communication in the simulator can then take place via the proprietary bus interface and on the receiver side it is transformed back to fmi-ls-bus data."
Can you try to start from that and not use attributes not previously defined (like "non-primary FMI importers")?

**Comment by bmenne-dspace** [comment]
@andreas-junghanns whats about: "The usage of this architecture type allows the integration of this layered standard into an already existing simulator, which implements network communication with proparity interfaces." instead of "Using this type of architecture allows the support of this layered standard for non-primary FMI importers by using proprietary extension mechanisms."

**Comment by bmenne-dspace** [comment]
@andreas-junghanns changes done I'm looking forward to the approve of this PR :)

**Review by andreas-junghanns — APPROVED** [review]

**Pull request merged**
