### PR TITLE
Complete CAN section

### PR DESCRIPTION
**Pull request by PTaeuberDS**
- Restructuring and expansion of the CAN chapter
- Minor adjustments in the Network Abstraction section

@andreas-junghanns @chrbertsch 
The document is now in a state for a first review.

### CODE REVIEW

**Review by andreas-junghanns — CHANGES_REQUESTED** [review]
principles_of_communication_complex.svg: in the image the "old" descriptions survived: "Confirm transmission" needs to be reduced to Confirm

**Review by andreas-junghanns — CHANGES_REQUESTED** [review]
- Figure 6: here you still have "Confirm Transmission", should be "Confirm" only
 - "The point in time in which FMUs will (potentially) send new network messages must be given to the importer in advance." - This is a "requires", I think we should only recommend. Using triggered clocks is not nice, but why forbit it? See also 4.3.1 where we seem to be more lenient.
 - 4.5.1. Direct Confirmation Parameter: Here we need to set a default value (start value) to true and must define that the FMU must confirm itself - otherwise we require all importers to understand the layered standard in order to exectute the FMU properly.
 - all tables should have numbers and titles for easier referencing
 - CAN op table: the total size column has (4 bytes) entries
 - Do we clarify anywhere, how to pack the Transmit Frame w.r.t. the bits? (add reserve bits to pad the bytes to also clarify bit position?)
 - The "OP Code" descriptions in the frame tables could contain the extual OP code.
 - W.r.t. previous comment: we now have some redundancy in the document: the overview table of all frame kinds and each individual, detailed description: dangerous. Maybe we remove the table in 4.7.1.1. Overview?

**Comment by PTaeuberDS** [comment]
> * "The point in time in which FMUs will (potentially) send new network messages must be given to the importer in advance." - This is a "requires", I think we should only recommend. Using triggered clocks is not nice, but why forbit it? See also 4.3.1 where we seem to be more lenient.

Allowing this could be critical for the overall simulation system. E.g., if one FMU uses triggered clocks while all the other ones are only using countdown clocks and are not capable of (re-)setting the FMU state.
We should discuss this point in the next meeting.

> * CAN op table: the total size column has (4 bytes) entries

Can you explain what you mean? Do you mean the "(4 bytes)" phrase should be removed from the individual cells and added to the heading because it applies to the entire column?

> 
> * Do we clarify anywhere, how to pack the Transmit Frame w.r.t. the bits? (add reserve bits to pad the bytes to also clarify bit position?)

Not sure what exactly you mean. We define the byte order and this implicitly includes the bit order. We defined padding bits after the flag bits. Is there something missing?

> * W.r.t. previous comment: we now have some redundancy in the document: the overview table of all frame kinds and each individual, detailed description: dangerous. Maybe we remove the table in 4.7.1.1. Overview?

We should discuss the pros and cons in the next meeting.

To the other points: We'll fix that :)

**Comment by oliverkotte** [comment]
current transmit behavior: 'The next Transmission operation shall only be sent as soon as there is a confirmation or an error.'
- In SiL, we can safely assume that sent messages are received. For many tests, confirm is not necessary. Having to respond with superfluous confirm messages to EACH transmit message might not be the best solution (at least for performance-focused fixed-step simulation).
- In solution space, one idea is to allow org.fmi-standard.fmi-ls-bus.DirectConfirmation=True for all use cases, not just Direct Communication. If True, a bus simulation FMU would not send confirm messages.
- Is bulk-sending multiple transmits in a single message for fixed-step simulation compatible with mandatory confirm/error between transmits? If so, we need to explain it.
	
structure the OPcode value range
- introduce reserved, today unused regions (e.g. for future CAN XXL after CAN XL)
- for different protocols, use same Opcodes when meaningful, e.g. for Tx, Rx, Error?

**Comment by chrbertsch** [comment]
> Since issues are created, I think we agreed on merging this, right?

Yes, please merge.

**Pull request merged**
