### PR TITLE
Add tools list for fmi-ls-bus landing page

### PR DESCRIPTION
**Pull request by bmenne-dspace**
see #185

### CODE REVIEW

**Comment by bmenne-dspace** [comment]
For a suggestion of a tools list within the fmi-ls-bus landing page see https://github.com/bmenne-dspace/fmi-ls-bus#tools

This list may not be complete and does not have to be ultimately reliable. At first it is a suggestion and after this it has to be checked by the tool vendors itself.

We can talk about this suggestion in one of the next FMI meetings.

**Comment by bmenne-dspace** [comment]
@masoud-najafi, @klausschuch, @snps-ribbe: I updated the preview (see https://github.com/bmenne-dspace/fmi-ls-bus#tools) and have also adapted everything as discussed in the last FMI design meeting. I cannot fill in the requested new column "Remarks" for you. You also have to check whether the information is correct for your importer. I have tried to make sure it is correct, but I still cannot judge it completely. BTW: If there is too much content within the new column the table layout gets easily ugly. Maybe we need a solution for this too.

**Comment by bmenne-dspace** [comment]
@klausschuch and @snps-ribbe can you also watch the whole thing?

**Comment by bmenne-dspace** [comment]
@klausschuch can you check?

**Comment by bmenne-dspace** [comment]
@snps-ribbe can you also check? Then we can merge that PR.

**Review by klausschuch — APPROVED** [review]

**Review by snps-ribbe — APPROVED** [review]
I approve the overview - especially the Silver capabilities.

**Pull request merged**
