### PR TITLE
Add initial operation for LIN bus

### PR DESCRIPTION
**Pull request by bmenne-dspace**
Add initial operation for LIN bus

### CODE REVIEW

**Comment by bmenne-dspace** [comment]
@andreas-junghanns this is our first proposal for LIN operations. Maybe we should just merge it?! We will write additional content (explaining chapters) like within the CAN part and can verify it if the specification for LIN is complete.

**Comment by chrbertsch** [comment]
Design Webmeeting: Let's merge it and improve it later.

**Review by chrbertsch — APPROVED** [review]

**Comment by chrbertsch** [comment]
Should we merge this into main or into a different 1.1.0 branch?
We do not plan to release this in the 1.0.0 release ...

**Comment by bmenne-dspace** [comment]
> Should we merge this into main or into a different 1.1.0 branch? (@pmai , @andreas-junghanns ) We do not plan to release this in the 1.0.0 release ...

@chrbertsch I think we can merge it. During the F2F meeting in PB, @pmai 's idea was to remove the remaining chapters of the other buses for a 1.0.0 release and thus develop everything in a consolidated manner. We have to remove the (currently empty) chapters for LIN/FlexRay/Ethernet for 1.0.0 anyway.

**Review by chrbertsch — APPROVED** [review]

**Pull request merged**
